name: Build

on:
  push:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Flow.Launcher.Plugin.GuidConverter/Flow.Launcher.Plugin.GuidConverter.csproj
    - name: Build
      run: dotnet build --no-restore -c Release Flow.Launcher.Plugin.GuidConverter/Flow.Launcher.Plugin.GuidConverter.csproj
